# Generated by Django 3.2.3 on 2021-05-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_m',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/m/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_s',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails/s/'),
        ),
    ]
