# Generated by Django 3.2.3 on 2021-05-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_tempurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempurl',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tempurl',
            name='url',
        ),
        migrations.AddField(
            model_name='tempurl',
            name='image_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
    ]
