# Generated by Django 3.2.3 on 2021-05-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210519_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempurl',
            old_name='image_id',
            new_name='image',
        ),
    ]
